# Nome do workflow,
name: Pipeline CI/CD
# Quando o pipeline será disparado
on: 
  push:
    branches:
      - main
    paths: # Só se arquivos nessa página forem alterados
      - "src/**" # Só mudanças no código fonte
      - ".github/workflows/**" # Mudanças no próprio Pipelines
  workflow_dispatch: # habilitar o botão "Run workflow" no Github actions
  
jobs: 
  # Primeiro job: build
  build:
    runs-on: ubuntu-latest # imagem da maquina que vai ser usada no CI
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v5
      
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          Caches: "npm"
          caches-dependency-patch: package-lock.json

      - name: Instalação das dependências    
        run: npm install 

      - name: Rodar o build
        run: npm run build

  tests:
    runs-on: ubuntu-latest # imagem da maquina que vai ser usada no CI
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5
      
      - name: Instalação do Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          Caches: "npm"
          caches-dependency-patch: package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Instalar ESLint (se faltar)
        run: npm install eslint --save-dev
      
      - name: Rodar o lint    
        run: npm run lint

      - name: Verificar formatação    
        run: npm run format -- -- check

      - name: Rodar tests    
        run: npm run test
    
